name: Arduino Library CI

on: [pull_request, push, repository_dispatch]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        arduino-platform: ['main_platforms', 'arcada_platforms']
    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
      with:
         repository: adafruit/ci-arduino
         path: ci

    - name: pre-install
      run: bash ci/actions_install.sh

    - name: test platforms
      run: python3 ci/build_platform.py ${{ matrix.arduino-platform }}

    - name: clang
      run: python3 ci/run-clang-format.py -e "ci/*" -e "bin/*" -r . 

    - name: doxygen
      env:
        GH_REPO_TOKEN: ${{ secrets.GH_REPO_TOKEN }}
        PRETTYNAME : "Adafruit ST77XX Display Library"
      run: bash ci/doxy_gen_and_deploy.sh
